[WIP] Add tests for PIs
gtauzin/giotto-tda pull request #6
Opened 2020-01-30 18:48 UTC by wreise

#### What does this implement/fix? Explain your changes.
Test PIs. I do not manage to have a null PI for all inputs on the diagonal.

#### Any other comments?

2020-02-03 17:08 UTC, gtauzin requested changes
I just made one comment.

I think it would be better to use ``n_bins`` instead of ``n_values`` and ``_bin`` instead of ``_discretize`` but that's up to @ulupo

2020-02-03 17:08 UTC, gtauzin commented on gtda/diagrams/preprocessing.py
>          if self.metric in ['landscape', 'heat', 'betti', 'persistent_image']:
Move all the conditions on the metric inside the _discretize function (for all transformer using metrics)

2020-02-03 17:18 UTC, gtauzin requested changes

2020-02-03 17:18 UTC, gtauzin commented on gtda/diagrams/_metrics.py
> +    for k in range(2):
Call it axis instead of k and use [0, 1] instead of range.

2020-02-03 17:18 UTC, gtauzin commented
I think I know why you are experiencing this with points on the diagonal.

Make the changes and then I will merge and take over.

2020-02-03 17:41 UTC, wreise commented
> I just made one comment.
> 
> I think it would be better to use `n_bins` instead of `n_values` and `_bin` instead of `_discretize` but that's up to @ulupo

@gtauzin Ok for the name change. The parameter name change is quite significant: the feature Transformers have the `n_values` parameter, which is used in many places (including use_cases). Afaiac, if you think it's a good idea, I will make sure that everything works.

2020-02-04 10:07 UTC, gtauzin approved these changes

2020-02-04 10:08 UTC, merged